title: "Hamza Habib"
description: "EET Graduate • CNC maker • Python dev"
baseurl: ""
url: "https://habib13352.github.io"

#theme: minima
markdown: kramdown
permalink: pretty

collections:
  projects:
    output: true
